baseURL = "https://blog.renyddd.top/"
languageCode = "en-us"
title = "renyddd blog site"
theme = "ananke"

# 默认的内容语言
# defaultContentLanguage =      "zh-cn"
# 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true
hasCJKLanguage =              true


[taxonomies]
tag = "tags"
category = "categories"
seris = "series"
